"""empty message

Revision ID: 4b54f79b7d3e
Revises: fe43be2736a2
Create Date: 2019-07-23 22:56:06.841285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b54f79b7d3e'
down_revision = 'fe43be2736a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sname', sa.String(length=20), nullable=False),
    sa.Column('spic', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('dialogue',
    sa.Column('did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('durl', sa.String(length=100), nullable=False),
    sa.Column('dlyric', sa.Text(), nullable=False),
    sa.Column('dname', sa.String(length=20), nullable=False),
    sa.Column('dsid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dsid'], ['scene.sid'], ),
    sa.PrimaryKeyConstraint('did')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogue')
    op.drop_table('scene')
    # ### end Alembic commands ###
